[0m00:23:33.060258 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ef61c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110d74a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110d6f30>]}


============================== 00:23:33.102998 | 74d4d112-ecd4-47d9-9a44-38be699a730f ==============================
[0m00:23:33.102998 [info ] [MainThread]: Running with dbt=1.9.4
[0m00:23:33.104196 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/kara/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init netflix', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:23:33.184071 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/include/starter_project
[0m00:23:33.238609 [info ] [MainThread]: 
Your new dbt project "netflix" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:23:33.239731 [info ] [MainThread]: Setting up your profile.
[0m00:27:05.361903 [info ] [MainThread]: Profile netflix written to /Users/kara/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:27:05.520789 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 212.7666, "process_in_blocks": "0", "process_kernel_time": 1.574057, "process_mem_max_rss": "165191680", "process_out_blocks": "0", "process_user_time": 4.532179}
[0m00:27:05.523638 [debug] [MainThread]: Command `dbt init` succeeded at 00:27:05.522928 after 212.77 seconds
[0m00:27:05.525988 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1217d4d40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ef61c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x121b34c20>]}
[0m00:27:05.528112 [debug] [MainThread]: Flushing usage events
[0m00:27:07.097734 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:14:18.852096 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c4cd550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d7c3770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d7c3200>]}


============================== 01:14:18.862415 | 754ed12f-0c36-4704-a179-95940c34f921 ==============================
[0m01:14:18.862415 [info ] [MainThread]: Running with dbt=1.9.4
[0m01:14:18.867258 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/kara/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:14:18.868828 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/kara/Desktop/dbt-netflix/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:14:18.874424 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.30434605, "process_in_blocks": "0", "process_kernel_time": 0.541273, "process_mem_max_rss": "89567232", "process_out_blocks": "0", "process_user_time": 4.205612}
[0m01:14:18.892230 [debug] [MainThread]: Command `dbt run` failed at 01:14:18.891718 after 0.32 seconds
[0m01:14:18.899756 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d7c3410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d7c3470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d7c36b0>]}
[0m01:14:18.904432 [debug] [MainThread]: Flushing usage events
[0m01:14:20.120033 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:57:49.965456 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076df5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107cc7500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107cc7110>]}


============================== 01:57:49.983076 | 613180e5-d123-408f-bcf3-93950ae8aeab ==============================
[0m01:57:49.983076 [info ] [MainThread]: Running with dbt=1.9.4
[0m01:57:49.985502 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/kara/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:57:49.986967 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/kara/Desktop/dbt-netflix/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:57:50.007133 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.5430924, "process_in_blocks": "0", "process_kernel_time": 0.606815, "process_mem_max_rss": "90075136", "process_out_blocks": "0", "process_user_time": 3.274857}
[0m01:57:50.008530 [debug] [MainThread]: Command `dbt run` failed at 01:57:50.008239 after 0.54 seconds
[0m01:57:50.009600 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103a2aea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c4f0e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b243b0>]}
[0m01:57:50.010975 [debug] [MainThread]: Flushing usage events
[0m01:57:51.512113 [debug] [MainThread]: An error was encountered while trying to flush usage events
